use soroban_sdk::contracterror;

/// Custom errors for the SoroStream contract (≤50 variants for Soroban XDR).
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum StreamError {
    StreamNotFound = 1,
    NotRecipient = 2,
    NotSender = 3,
    StreamNotActive = 4,
    ZeroAmount = 5,
    InvalidDuration = 6,
    InvalidCliff = 8,
    AlreadyInitialized = 9,
    NotInitialized = 10,
    DuplicateStream = 11,
    ContractPaused = 14,
    Overflow = 15,
    ZeroFlowRate = 16,
    BatchLengthMismatch = 17,
    TokenMismatch = 18,
    StreamLocked = 19,
    NotAuthorized = 20,
    StreamNotPaused = 21,
    StreamDurationTooShort = 22,
    InvalidNonce = 25,
    MigrationAlreadyApplied = 26,
    StreamNotSettled = 27,
    WithdrawalCooldownActive = 28,
    RecipientNotWhitelisted = 29,
    InvalidEndTime = 31,
    ReentrancyDetected = 34,
    InvalidMetadataUri = 35,
    StreamNotComplete = 36,
    TokenNotWhitelisted = 37,
    InvalidTranches = 38,
    RateLimitExceeded = 41,
    InvalidSlippage = 43,
    DurationExceedsMax = 44,
    InvalidTokenAddress = 45,
    StartTimeTooFar = 46,
    IDCollision = 47,
    NextStepNotReached = 48,
    AmountBelowMinimum = 49,
    InvalidExpiryWindow = 50,
    NewSenderStreamCapExceeded = 51,
    InvalidRedirectTarget = 52,
    CircularRedirect = 53,
    RedirectRecipientMismatch = 54,
    PriceDeviationTooHigh = 56,
    TokenStreamCapExceeded = 57,
    AddressBlocked = 58,
    StreamNonTransferable = 59,
    /// The stream's end_time has passed but the grace period is still active.
    GracePeriodActive = 60,
    AwaitingApproval = 61,
    InvalidPartialCancel = 63,
    MaxDepositExceeded = 64,
}
